### ISSUE TITLE
some interface was not exist in this api

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs-http-client#25] opened 2019-08-12 05:27 UTC
I am sorry to be bothered many times.
now i has two questions:
1. in this package `/api/v0/add` was not found. will add this interface later?

2. `(api *PinAPI) Ls(ctx context.Context, opts ...caopts.PinLsOption)` has no `arg` parameter to input.
i see the `https://docs.ipfs.io/reference/api/http/#api-v0-pin-ls` has it.
and i neet it now. will add this parameter in this interface ?

**Comment by Stebalien** [comment] 2019-08-12 23:23
> 1

`api.Unixfs().Add(...)`?

> 2

We'd probably add a new function. Something like `Pin().Has(ctx, path)` or `Pin().IsPinned(...)`. Note: At least in the current implementation, this is unlikely to be any faster than simply listing all pins and checking if the target path is in the list of pinned paths.

**Comment by godcong** [comment] 2019-08-13 07:28
> `api.Unixfs().Add(...)`?
yes,it is.
>We'd probably add a new function. Something like Pin().Has(ctx, path) or Pin().IsPinned(...). 
perhaps i can help to do this, :)
> Note: At least in the current implementation, this is unlikely to be any faster than simply listing all pins and checking if the target path is in the list of pinned paths.
at first,I have been using `ipfs pin ls`.
but when the data is very large, it always suspended、did not return any information. 
the rest api `/api/v0/pin/ls` has the same problem.(their implementation should be the same)
type `recursive` can temporarily solve some problems.

**So i think perhaps we need a pipeline interface to output informations,But I don't know if this is easy to implement.**
or reduce the scope of the search. like add a `Pin().IsPinned(...).` interface.

**Comment by Stebalien** [comment] 2019-08-16 04:10
What are you _actually_ trying to do here?

**Comment by godcong** [comment] 2019-08-16 05:19
>What are you actually trying to do here?

`pin ls` looks a bit slow

now an arguments of type `recursive`  can let me get the `pin` list with a long time.
because, i can't get any information when used default type.

Is there any good advice?

**Comment by Stebalien** [comment] 2019-08-16 07:24
I can't understand what you're trying to say.

**Comment by godcong** [comment] 2019-08-16 08:30
I only want to get the `pin` list. 
`(api *PinAPI) Ls(ctx context.Context, opts ...caopts.PinLsOption)` has no response for me.

This may not be solved by this api.

**Comment by Stebalien** [comment] 2019-08-16 20:12
Got it. The issue is that it's recursively generating the pin list server-side.

* go-ipfs master (not released) can _stream_ pins when passed the `--stream` flag.
* If you only want a list of files you've _explicitly_ pinned, you can pass `--type=recursive` to `ipfs pin ls`. By default, `ipfs pin ls` prints out all pinned _blocks_, which includes everything referenced by a directly pinned file.

That's why I asked what you're trying to do. Unfortunately, `ipfs pin ls SomeThing` will _also_ check if that thing is pinned indirectly (unless you pass `--type=recursive` or `--type=direct`). It's not going to be any faster than `pin ls`.

**Comment by godcong** [comment] 2019-08-17 09:12
Yes, as you said.
This is the problem I am having now.

>go-ipfs master (not released) can stream pins when passed the --stream flag.

I saw it. 
Does `go-ipfs-http-client`  plan to add similar features in the future?
This seems to be a more complicated function for `go-ipfs-http-client`.

**Comment by Stebalien** [comment] 2019-08-19 14:53
> Does go-ipfs-http-client plan to add similar features in the future?

Yes. There's already a patch for github.com/ipfs/go-ipfs-api (https://github.com/ipfs/go-ipfs-api/pull/190). However, that's blocked on releasing the feature in go-ipfs.

>  close this?

I've filed two issues:

#27 
#28

If those cover it, let's close this one.

**Comment by godcong** [comment] 2019-08-19 19:30
OK, thanks

**Closed** 2019-08-19 21:32 UTC
